### PR TITLE
created the otp page and linked it to interests

### LINKED ISSUE #9: add dob and year group fields frontend
Add extra fields in sign up for login and sign up

### LINKED ISSUE #10: frontend otp page addition
OTP page for email OTP

### PR DESCRIPTION
**Pull request by kwakuNti**
The verification page for the otp

### CODE REVIEW

**Review by Joseph-Lartey — APPROVED** [review]

**Review by buzbunny — APPROVED** [review]
Linked the pages  and disabled the buttons until all input files were filled

**Review by buzbunny — APPROVED** [review]
Added the top

**Review by P-Asare — CHANGES_REQUESTED** [review]
1. I think it will be best if the OTP comes before you even pick your interest. Cause if your email is not verified we will discard your interests anyway.

2. The scrolling error is still occurring. Wrap the child of the container that has the text in it with a SinglechildScrollView.

3. Can you enlarge the icons on the bottom bar? They seem small on an Android.

4. Can you also resolve the const suggestions like the last time around?

image

**Review by P-Asare — APPROVED** [review]
Changes look solid to me. I believe the other changes were made by @kwakuNti  on another branch so that's cool. 💪

**Pull request merged**
